version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/clojure:1.12.0-openjdk-17.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "project.clj" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-deps-{{ checksum "project.clj" }}
      - run:
          name: Compile project
          command: lein compile
      - run:
          name: Run tests
          command: lein test
      - run:
          name: Check for compilation warnings
          command: lein check

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
